### ISSUE TITLE
Update the Navbar to make in responsive

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#1]
## 🚀 Feature

**Design the navigation bar**

Basic Navbar using html and vanilla css

**Comment by tm2k23** [comment]
Hey @code-soham can u please assign this to me? 
I will do it without bootstrapping

**Comment by tm2k23** [comment]
I have designed the navbar, kindly check the pull request

**Comment by ItsRoy69** [comment]
Sir can I get assigned under Hacktoberfest?
