### ISSUE TITLE
Modifying the Landing page

### ISSUE THREAD

**Issue by 19082002** [gdscjgec/Pictionary#10]
## 🚀 Feature   

**change ui design for home page**
Adding some Styles to the page using CSS and a digital clock to the footer.
**want to make the page responsive**
Rectify the overlaps..

Adding a navigation bar to the all page so that the user can directly go back to the home page...

**Comment by TishaJhabak1014** [comment]
Can I work on this? @19082002

**Comment by code-soham** [comment]
@19082002 assigned!

**Comment by ItsRoy69** [comment]
Can I work on this?
