### ISSUE TITLE
Remove the darkmode and clean the code

### ISSUE THREAD

**Issue by AtriSukul1508** [gdscjgec/Pictionary#107]
## Describe the Bug 🐛
Remove the darkmode functionality and clean the code
**A clear and concise description of what the bug is**
Darkmode on the website is not working properly.If we enable dark mode the colors get inverted
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AtriSukul1508** [comment]
I would like to work on this issue under JWOC

**Comment by code-soham** [comment]
Assigned!
