### ISSUE TITLE
Navbar bug in Contributors Page

### ISSUE THREAD

**Issue by Shruti025** [gdscjgec/Pictionary#118]
## Describe the Bug 🐛

**The navbar in the Contributors Page is larger than the required size**

**Screenshots**
![image](https://media.discordapp.net/attachments/937232718406766613/945693138868129882/unknown.png?width=856&height=586)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by Sanghu01** [comment]
I would like to work on this issue under JWOC plz assign me also.
