### ISSUE TITLE
Alignment problem in the footer section of Contributor page 

### ISSUE THREAD

**Issue by sayan404** [gdscjgec/Pictionary#119]
## 🚀 Feature

The text of footer section of Contributor page has no proper alignment.

**Is your feature request related to a problem? Please describe.**
![footer_problem](https://user-images.githubusercontent.com/95490367/155375316-9a40d23d-0bad-44d8-bbfa-f90610cdc83b.png)

**Describe the solution you

'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by code-soham** [comment]
Hi @sayan404 , already the contributors page is being worked upon, so after that PR is reviewd I'll surely assign you this issue if problem persists! :)
