### ISSUE TITLE
I the Contributor page links should open in the new window for better user experience

### ISSUE THREAD

**Issue by sayan404** [gdscjgec/Pictionary#120]
## 🚀 Feature

I the Contributor page links should open in the new window for better user experience

**Is your feature request related to a problem? Please describe.**
(https://drive.google.com/file/d/1yog9eDeYiDXDZVAMjmjV0vMS-gSmkgyB/view?usp=sharing)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by code-soham** [comment]
generally external links open in new tabs , so I believe this isn't necessary
