### ISSUE TITLE
contrast color combination

### ISSUE THREAD

**Issue by gullapalli9482** [gdscjgec/Pictionary#123]
Usage of proper colors to the website would make the website more appealing, Than extreme color combinations , making it uncomfortable to glance

**Comment by gullapalli9482** [comment]
Anything easy to view would do.

**Comment by code-soham** [comment]
Would you like to take up this issue? If so, do elaborate else I'll mark it up for grab if required

**Comment by Faraaz2633** [comment]
Hey there, 
I would like to work on this issue under JWOC.
could you please assign it to me?
