### ISSUE TITLE
Gallary link is not working for Quick Links

### ISSUE THREAD

**Issue by Jyoti6828** [gdscjgec/Pictionary#126]
## Description: 
In the footer of the home page, there are Quick links for -
- Gallery
- About Us
- Contributors
But for Gallary It not working: 
 
### Screenshot: 
![image](https://user-images.githubusercontent.com/78480983/156722984-4e2b711e-5063-4e1e-b57d-e52fb52c1e16.png)

**Comment by Jyoti6828** [comment]
I want to work on this issue under JWOC.

**Comment by code-soham** [comment]
@Jyoti6828 Assigned!
