### ISSUE TITLE
Revamp the existing Navigation Bar

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#13]
## 🚀 Feature 
**Revamp existing navigation bar** 

Navbar should have the basic items , a branding logo (left) , and the menu options on the right. 
Create a responsive dropdown for the Navbar, on smallest viewports with same functionality.

**Comment by lejara** [comment]
hello, may i work on this?

**Comment by harshalw07** [comment]
Hello @code-soham I am intrested to work on this issue ,
I will make navbar owsome.......

**Comment by SushantBarje** [comment]
Hi @code-soham, I am interested in this. Can you assign this issue to me?

**Comment by TuhinBanerjeeCSE** [comment]
I want to work on this issue. I'm a member of gdsc jgec .

**Comment by code-soham** [comment]
> I want to work on this issue. I'm a member of gdsc jgec .

Assigned @TuhinBanerjeeCSE

**Comment by KOMAL729** [comment]
hey , can i work on this?

**Comment by niloysikdar** [comment]
It's been already 4 days @TuhinBanerjeeCSE . Unassigning you.
Assigned you @yas-sisodia

**Comment by wasimreja** [comment]
@niloysikdar Can you assign this to me if it's not done?
