### ISSUE TITLE
Dark Mode feature

### ISSUE THREAD

**Issue by archanagandhi** [gdscjgec/Pictionary#15]
## 🚀 Feature

**A clear and concise description of what the feature is.**
Adding dark mode feature to the web page

**Is your feature request related to a problem? Please describe.**
Everybody prefers dark mode when comes to website

**Describe the solution you'd like**
I would like to add a new feature, Dark mode. 
Please assign this to me. So i can start working

**Comment by SubrataMondal18** [comment]
I want to work on this issue under GDSC JGEC, please assign this to me !!

**Comment by niloysikdar** [comment]
Hey @archanagandhi , assigned you, go ahead. All the best.
