### ISSUE TITLE
Navbar logo and navbar item links are faulty

### ISSUE THREAD

**Issue by mnaiwrit52** [gdscjgec/Pictionary#17]
## Describe the Bug 🐛

**A clear and concise description of what the bug is**
On clicking Pictionary logo as well as the home button, the page doesn't reload to index.html, thereby giving a faulty page.

**To Reproduce**

1. Go to navbar on the first page.
2. Click on 'Home' or 'Pictionary' logo.
3. See faulty page opens with a message.
4. Also you are unable to navigate from gallery page to about page and vice versa

**Expected behavior**
Navigation from one page to another should be possible.

**Issue screenshots similar to this**
![image](https://user-images.githubusercontent.com/71037548/135964073-a866c123-7713-44cd-82aa-19a7c06536e4.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : Chrome

**Comment by mnaiwrit52** [comment]
### Please assign 🤓

**Comment by rajputarjun2001** [comment]
Hi @mnaiwrit52 , I want to work on this issue, Could you please assign this to me?

**Comment by maihunsandip** [comment]
I would like to work on this.. I'm member of GDSC jGEC.

**Comment by Yash-RajSingh** [comment]
I can take up this issue. Please assign it to me @mnaiwrit52

**Comment by niloysikdar** [comment]
Hey @mnaiwrit52 , assigned you the issue.
