### ISSUE TITLE
Prettify the Gallery Overview Page 

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#2]
## 🚀 Feature

###Add life to the gallery!

The gallery overview will contain the different topics/categories the our pictionary will consist of.
It should contain a list of topics each of which leads to the respective topic page(to be added on the go , in its suitable position in directory).

**Comment by ItsRoy69** [comment]
Sir can I get assigned under Hacktoberfest?

**Comment by roshanmelanta** [comment]
Hi, can you assign me this issue? I'll use cards to properly align all the categories along with images

**Comment by TuhinBanerjeeCSE** [comment]
I would like to work on this issue. I am member of gdsc jgec .

**Comment by yadavashishdhirendra** [comment]
Hey @code-soham I would Like to work on this issue If you have many data in gallery section Then I would like to fetch it through JSON can u please assign it to me under hacktoberfest!

**Comment by code-soham** [comment]
> Hey @code-soham I would Like to work on this issue If you have many data in gallery section Then I would like to fetch it through JSON can u please assign it to me under hacktoberfest!

this is something we really have in mind after we are done with a full basic website! Stay tuned!

**Comment by yadavashishdhirendra** [comment]
> > Hey @code-soham I would Like to work on this issue If you have many data in gallery section Then I would like to fetch it through JSON can u please assign it to me under hacktoberfest!
> 
> this is something we really have in mind after we are done with a full basic website! Stay tuned!

Waiting for That feature @code-soham!
