### ISSUE TITLE
Add Landing page content

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#22]

**Comment by Alahoz** [comment]
Hi! Can I get this issue?

**Comment by Yash-RajSingh** [comment]
I can take up this issue. Please assign it to me @code-soham

**Comment by niloysikdar** [comment]
Assigned you @Alahoz , will assign @Yash-RajSingh if the issue won't get resolved within 1 day.

**Comment by Yash-RajSingh** [comment]
> Assigned you @Alahoz , will assign @Yash-RajSingh if the issue won't get resolved within 1 day.

Has this issue been attended to now or can i take this up?

**Comment by Yash-RajSingh** [comment]
> Assigned you @Yash-RajSingh

I've added the best suited information and details about the website on the landing page in the PR #46 . Kindly check and merge.
