### ISSUE TITLE
The gallery cards are not responsive and centered

### ISSUE THREAD

**Issue by Pratham-Mishra178** [gdscjgec/Pictionary#25]
## The gallery cards are not responsive and centered 🐛

**When we go to the gallery section we can find that the cards are not centered properly.**

**To Reproduce**

1. Go to 'Website'
2. Click on 'Gallery'
3. You can see that the gallery cards are not centered properly within the window.

**Expected behavior**
all the cards should be aligned to the center.

**Screenshots**
![Screenshot (619)](https://user-images.githubusercontent.com/78583437/136085751-bc1bcd5a-657b-4bb0-9d81-20faeb920a06.png)

**Desktop:**

- OS: Windows 10
- Browser: Chrome
- Version: Version 94.0.4606.61 (Official Build) (64-bit)

**Additional context**
Please assign me this task under hacktober fest 2021 so that I can resolve this issue ASAP.

**Comment by Pratham-Mishra178** [comment]
Please assign me this task under  Hacktober fest 2021

**Comment by mayankgoyal-13** [comment]
The pull request #28 resolves this issue
