### ISSUE TITLE
Footer is not responsive

### ISSUE THREAD

**Issue by shubhamjha25** [gdscjgec/Pictionary#26]
**A Clear and Concise Description of What the Bug is**
The footer of the website is not responsive.
When the screen size shrinks, it looks quite ugly.

**To Reproduce**
1. Go to the Website
2. Scroll down to the bottom where the footer is
3. Right Click > Then Inspect
4. It's Clearly visible that it's not responsive
(Also attached the screenshot below)

**Expected Behavior**
The items of the footer should be aligned properly.

**Screenshots**
![WhatsApp Image 2021-10-06 at 00 30 39](https://user-images.githubusercontent.com/63443481/136086283-87a4f744-9f05-4210-8419-8cc919742aef.jpeg)

**Smartphone (please complete the following information):**
- Device: Vivo Y-15
- OS: Android
- Browser: Google Chrome
- Version: Android 11

**Additional context**
Please assign me to this issue so that I can start working on this as soon as possible.
Thanks! 😀

**Comment by niloysikdar** [comment]
Assigned @shubhamjha25
