### ISSUE TITLE
Add CONTRIBUTORS.MD

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#3]
## 📚 Documentation

###Incorporate a contributors.md page to list contributions for future PRs ###

Helps to keep track and give the credit contributors deserve.

Basic Structure :
Heading
Contributors:
                 Name, Github-link, Contribution-specifics

**Comment by ItsRoy69** [comment]
Sir can I get assigned under Hacktoberfest?

**Comment by VidhiBhatt01** [comment]
I would like to work on this, please assign. (Am a part of GDSC JGEC)

**Comment by niloysikdar** [comment]
Assiged @ItsRoy69, will assign @VidhiBhatt01 after 2 days if it won't complete.
