### ISSUE TITLE
Add Birds to the bird gallery 

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#5]
## 🚀 Feature

**A clear and concise description of what the feature is.**

Add a page for birds gallery in the file-tree and continue with it.

Create card template and populate with data of common birds. 

Requirements: Common Name, Scientific Name, Distribution, Description, Food habits

![Common Name](https://user-images.githubusercontent.com/77236783/135676106-956b6b22-e0da-4624-afd6-6337ee1bf9bb.png)

Design card-like format with smooth edges loosely based on above sketch.

**Comment by vivekkj123** [comment]
Assign this issue to me. Let me work on it

**Comment by pavithra-064** [comment]
can you please assign me this

**Comment by SubrataMondal18** [comment]
@code-soham I want to work it on under GDSC JGEC , can you assign this ?

**Comment by code-soham** [comment]
> @code-soham I want to work it on under GDSC JGEC , can you assign this ?

Will assign @SubrataMondal18  if it isn't completed by @pavithra-064 by tomorrow

**Comment by code-soham** [comment]
@SubrataMondal18 assigned

**Comment by rrriiiyyyaaa** [comment]
Please review my PRs #35

**Comment by rrriiiyyyaaa** [comment]
> > Please review my PRs #35
> 
> Sorry, but pr #35 was created and submitted by me. Please don't lie like this

Really sorry, I updated now. My mistake sorry. I didn't notice
