### ISSUE TITLE
Relink the Navigation links to Correct pages

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#52]
## Describe the Bug 🐛

**A clear and concise description of what the bug is**

**To Reproduce**
(for larger screens only)
1. Go to 'Navbar'
2. Click on 'Home Button'
3. See error

**Expected behavior**
Pictionary home screen appears

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
//not applicable

**Comment by Shruti025** [comment]
I want to work on this issue under JWOC

**Comment by harshit4021** [comment]
I want to work on this issue under JWOC

**Comment by code-soham** [comment]
> I want to work on this issue under JWOC

@Shruti025 assigned! All the best!
