### ISSUE TITLE
a hamburger menu  could be enabled to enhance the UI enclosing the 4 links 

### ISSUE THREAD

**Issue by harshit4021** [gdscjgec/Pictionary#53]
## 🚀 Feature

**A clear and concise description of what the feature is.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshit4021** [comment]
"I want to work on this issue under JWOC"

**Comment by manishbajagai2** [comment]
I want to work on this issue under JWOC

**Comment by code-soham** [comment]
I believe the issue you're talking of is in the landing page, while in some other pages the hamburger menu is styled. I would really like you to tally them and make them alike ! Thanks!
@harshit4021 Assigned

**Comment by code-soham** [comment]
@harshit4021 Hey harshit, could you update me with the progress on this issue?
thanks, Soham
