### ISSUE TITLE
Grammatical errors

### ISSUE THREAD

**Issue by manishbajagai2** [gdscjgec/Pictionary#54]
## Describe the Bug 🐛

**It is a simple bug anyone can notice and resolve. There is a potential spelling error in the About Us Page**

**To Reproduce**

1. Go to About Us in the NavBar
2. In the Who Are We? section check out for potential errors

**Expected behavior**
Spelling mistakes are to be taken care of, some more gramatical mistakes eeds to be fixed

**Screenshots**
![image](https://user-images.githubusercontent.com/62448303/151853897-c73669df-d44f-479c-9a24-79ab4fa5606f.png)

**Desktop (please complete the following information):**

- OS: [MacBook Air]
- Browser [Chrome]
- Version [97.0.4692.99]

**Comment by code-soham** [comment]
@Kaggrov If you're doing this, make sure to check for such mistakes throughout the site! 
Assigning it to you .

**Comment by Kaggrov** [comment]
ok sir
