### ISSUE TITLE
Populating the cards with actual data

### ISSUE THREAD

**Issue by Sanga-Pal** [gdscjgec/Pictionary#56]
## Describe the Bug 🐛

The cards doesn't show their proper description instead contains default text.
![Screenshot 2022-02-01 102308](https://user-images.githubusercontent.com/97869216/151914914-092cdef4-062c-406f-8490-ae6621834744.jpg)

**To Reproduce**

1. Go to 'Home'
2. Click on 'Gallery'
3. Scroll down to 'Cards'
4. Click on the cards 
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by code-soham** [comment]
@Sanga-Pal assigned! All the best ;)
