### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#57]
## 🚀 Feature

**Theme the Website uniformly across all existing pages.**

All the pages should be redesigned to have a light and a dark mode, that can be switched by the client.

**Solution I'd like**
You may use global parent class definition to dynamically switch between CSS classes.
You may even implement SCSS if needed.

**Alternatives I've considered**
Go creative!

P.S. theming is key 😉

**Comment by Debdeep1** [comment]
I want to work on this issue under JWOC.

**Comment by code-soham** [comment]
Looking forward to an awesome themed ui!

**Comment by DarkFalc0n** [comment]
I want to work on this issue under JWOC
