### ISSUE TITLE
Suggest a new Card design for contributors feature page!

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#58]
## 🚀 Feature
 **Design (No coding involved)**
Suggest a good design for the contributors card,
you can check out the current layout from 

[Contributors Page](https://gdscjgec.github.io/Pictionary/contributors.html)

I am looking forward to automate the contributors page using Github API, so
I would like a simple yet concise card design.

Here's the APIs, so you may decide what all data can be presented and how they will be presented in your design.

**Suggested Keeps**

- username
- avatar
- profile link (hover click button)
- followers count
- contributions made (to our repo)

Go creative with the design!
Looking forward to Light and Dark Modes, as we will be also getting our themes revamped soon enough!

The APIs (for reference only) :
https://api.github.com/users/{username}    [ personal profile data ]
https://api.github.com/repos/{org}/{repo-name}/contributors  [ contributors API ]

```
USAGE : 
https://api.github.com/users/code-soham
https://api.github.com/repos/gdscjgec/Pictionary/contributors
```

**NOTE to mentees :**
Once done, we would be looking forward with the coding part , so stay tuned !

**Comment by ronitblenz** [comment]
Hi, I am interested in this issue. Please let me in as an assignee

**Comment by code-soham** [comment]
Okay @ronitblenz , I am assigning it to you! 👍🏻
Have fun designing! ;)

**Comment by code-soham** [comment]
To upload your work for the PR, what you could do is create a folder in the root directory called "designs" and then create a subfolder for your work , obviously maintaining the other norms of contribution as they are. @ronitblenz

**Comment by ronitblenz** [comment]
Can you please give me a sample of what I need to do?

**Comment by code-soham** [comment]
@ronitblenz you can take references from here - https://freefrontend.com/css-cards/

**Comment by ronitblenz** [comment]
Ouk ouk gotcha... I have time upto tomorrow evening right?

**Comment by code-soham** [comment]
This is a medium issue, so I think 2 days would be enough to ideate the design only.. 
So you'll have till 4th Feb, evening (i.e. 48 hrs since assignment of issue)
If you're defaulting, it will be passed to the next assignee, if there.

**Comment by ronitblenz** [comment]
ok thank you, where can I connect with you any social handles?

**Comment by code-soham** [comment]
@ronitblenz you can find me on our JWOC discord server channel for the repo and dm me there, the discord link I'm sure you received in the welcoming mail if not you can mail the authority Directly for any assistance, and also contact me by mail as well. I wont be sharing my personal contact here🥲, dm .

**Comment by ronitblenz** [comment]
I understand ...XD I will find you in the server hehe..
