### ISSUE TITLE
Improving the Gallery page

### ISSUE THREAD

**Issue by Rohan-Hazari** [gdscjgec/Pictionary#62]
Putting space between images to not trigger the hover effect 
to resolve any problem causing overflow

**Comment by coder-mohit** [comment]
hey can you elaborate the bug in more detail

**Comment by Rohan-Hazari** [comment]
Umm it was my first time raising an issue so it is not actually a bug but at few devices dimension the images start overflowing

**Comment by code-soham** [comment]
@Rohan-Hazari Hi there! I'm assigning it to you!
Make sure to ensure the gallery page layout holds well in all screen sizes and also revamp the Card CSS for maintaining a uniform dimensions! All the best!
