### ISSUE TITLE
Adding Navbar to Gallery and Contribution page

### ISSUE THREAD

**Issue by aadrikasingh18** [gdscjgec/Pictionary#63]
I can add a Navbar to both the pages and that will help in navigation.

**Comment by aadrikasingh18** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by code-soham** [comment]
@aadrikasingh18 Hi there! I'd be glad that you're taking up this issue, but before going on, kindly update the Issue in the correct format as given by the official template!
thanks! ;)

**Comment by aadrikasingh18** [comment]
Sure I am doing it that way.

**Comment by aadrikasingh18** [comment]
Sorry for the inconvenience

**Comment by aadrikasingh18** [comment]
But can you pls tell me where can I find the template? Or I have to make it on my own seeing other issues?

**Comment by code-soham** [comment]
@aadrikasingh18 the template should have come up on its own  when you open the new issue page.. if it didn't, just make sure to add some description to your issue, with what your  want to do, any bugs(if there), stuff like that, nothing strict over there ;)

**Comment by aadrikasingh18** [comment]
I think it came but I was not sure what to write and I thought it had to be done who so ever assigns the issue. Will keep it in mind the next time. 

Thank you and will surely add the description at the time of pr.
