### ISSUE TITLE
Improving footer

### ISSUE THREAD

**Issue by manisha-27** [gdscjgec/Pictionary#64]
Improving the footer UI on the main page.

**Comment by code-soham** [comment]
Hey there @manisha-27 , if you're revamping the footer for our site, I would also like you to make the footer visible  across all the existing pages, as for now it's only on the landing page. 
Thanks! 
Assigning it to you! 

Some suggestions : 
Keep the footer minimal
Integrate the logo of Google developer club in the footer
Add mailing information for contact 

You may keep other details as per your choice! 

Good luck, have fun!

**Comment by code-soham** [comment]
@manisha-27 hey could you update me with the footer you're working on, if it's not a hassle ;)
thanks!

**Comment by manishbajagai2** [comment]
If possible i would like to give it a go. @code-soham can you please assign the issue to me.

**Comment by manishbajagai2** [comment]
I want to work on this issue under JWOC

**Comment by code-soham** [comment]
As we haven't heard back from @manisha-27 in these 3 days, transferring assignment to @manishbajagai2
