### ISSUE TITLE
A footer for the website

### ISSUE THREAD

**Issue by FireQueen-3010** [gdscjgec/Pictionary#7]
## 🚀 Feature

Adding a simple footer at least might make the website look complete.

**Describe the solution you'd like**
A footer with links to the main repo and links to different parts of the website.

**Comment by FireQueen-3010** [comment]
Please assign me this under hacktober fest

**Comment by niloysikdar** [comment]
Assigned @FireQueen-3010

**Comment by SoundaryaKhanapur** [comment]
May I take this up?
