### ISSUE TITLE
Nav-Links open in new tabs

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#70]
## Describe the Bug 🐛

**A clear and concise description of what the bug is**

**To Reproduce**

1. Go to '.Homepage'
2. Click on any link
3. See error

**Expected behavior**
Opening multiple tabs is hectic and unnecessary as we're already working on a functional navbar. So I'd like it to not prompt new tabs to open.

**Comment by code-soham** [comment]
@Koustavjr Assigned! :)

**Comment by Anosh21** [comment]
I would like to contribute in this issue under jwoc
I would like to collaborate with @Koustavjr on this issue.
