### ISSUE TITLE
Add Hamburger Menu to gallery and Contributors pages

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#75]
## Describe the Bug 🐛

**the hamburger menu in those pages arent functional**

**To Reproduce**

1. Go to 'Gallery'
2. Click on 'Dropdown'
3.  See error

**Expected behavior**
Dropdown menu should appear with links
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by harshit4021** [comment]
i want to work on this issue under jwoc

**Comment by Shruti025** [comment]
hey, can I work on this issue under JWOC?

**Comment by code-soham** [comment]
@Shruti025 Surely!
Keep please a note that you have to replicate the hamburger menu that's working in the other pages, and no need to implementing a different one ;)

**Comment by Shruti025** [comment]
oh alright, thanks for informing :)
