### ISSUE TITLE
Implement the Contributors Card Design

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#77]
## 🚀 Feature

**Actuate the card design for contributors page**

Steps to access the design :
```
Go to designs/Figma Card Design
View the design file
Replicate it and replace the existing card design
```

**No need to populate with actual data.**

**Comment by Sanga-Pal** [comment]
@code-soham I want to work on this issue under JWOC

**Comment by code-soham** [comment]
👍🏽 good luck
