### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by IAmTamal** [gdscjgec/Pictionary#8]
## 🚀 Feature

**A clean minimalistic about page.**

**Is your feature request related to a problem? Please describe.**
Nil

**Describe the solution you'd like**
Hello, i am Tamal from GDSC JGEC I would like to add a clean and minimalistic about page for the site.

**Describe alternatives you've considered**
Nil

**Additional context**
Nil.

**Comment by IAmTamal** [comment]
Sir, can i be assigned with the issue ?

**Comment by niloysikdar** [comment]
Assigned @IAmTamal

**Comment by IAmTamal** [comment]
The changes have been made, kindly review and merge the PR.
