### ISSUE TITLE
fix the position of darkmode toggle button in all pages

### ISSUE THREAD

**Issue by Mr-ram99** [gdscjgec/Pictionary#80]
Fix the position of darkmode toggle button 

Current problem
Dark mode toggle button in gallery, contribution, and other pages is at top-left hiding the logo of website. it should be in bottom right.

**Comment by Mr-ram99** [comment]
@code-soham Assign me this. I have already debugged the bug.

**Comment by code-soham** [comment]
Where are you putting the button after fixing?

**Comment by Mr-ram99** [comment]
at bottom right

**Comment by code-soham** [comment]
Okay I'm assigning to you , good luck!

**Comment by Mr-ram99** [comment]
check yourself - https://mr-ram99.github.io/Pictionary/    
let me know if you want any change.
