### ISSUE TITLE
Add site logo to navbar 

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#84]
## 🚀 Feature

The logo should be placed on the navbar (left corner) and also incorporated into the hamburger menu (centered) 
The logo can be taken from the README.md file on this repository.

Make sure to review the responsiveness of the navbar after the integration.

**Comment by manishbajagai2** [comment]
So basically replace the exising logo with the one found in readme ?

**Comment by manishbajagai2** [comment]
i want to work on this issue under JWOC
