### ISSUE TITLE
Creating a favicon for the website

### ISSUE THREAD

**Issue by manishbajagai2** [gdscjgec/Pictionary#85]
## 🚀 Feature

This feature helps the tab to stand out among other tabs in the web browser. Also most of the good websites have one.

**Is your feature request related to a problem? Please describe.**
It is not a problem not to have one but i a good practice

**Describe the solution you'd like**
May be resized and smaller version of the logo or creation of an icon with the initial letter would do fine.

**Comment by code-soham** [comment]
Yes, it'd be good to have the favicon as well, you may incorporate our logo, or come up with a design if you may wish to suggest one! Good luck!
