### ISSUE TITLE
Fix the gallery/landing.html page

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#89]
## Describe the Bug 🐛

**A clear and concise description of what the bug is**

open the gallery landing page

**Comment by manishbajagai2** [comment]
I think i fixed this issue in my previous pr @code-soham

**Comment by manishbajagai2** [comment]
Or if there is any let me work on it. Please let me know

**Comment by code-soham** [comment]
Okay I'll review the issue
