### ISSUE TITLE
Font family mismatch

### ISSUE THREAD

**Issue by manishbajagai2** [gdscjgec/Pictionary#90]
## Describe the Bug 🐛

I don't know if it really matters or not but the font family used in body and footer seems mismatch

**Expected behavior**
Please have a look if we shall keep it as it is or change to one

**Screenshots**

![Screenshot_2022-02-08-11-39-16-00_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/62448303/152928765-7a1a5d7b-2169-4875-a2a9-1cd8a1affda7.jpg)

**Comment by manishbajagai2** [comment]
@code-soham if changes need to be reflected. Let me work on it else you may close this issue 😃

**Comment by manishbajagai2** [comment]
Also just now i notice in the above screenshot that a little space is needed between the bullet and the topics mentioned

**Comment by code-soham** [comment]
what font family would you be suggesting to upgrade to?, I don't think this is a much needed fix but still it can be upgraded

**Comment by manishbajagai2** [comment]
I mean it's not like upgrading but you see in the above screenshot, the font family of the letter M in Movies and the font family of the letter M in Made with .., is not the same. I wanted to keep them in sync. So basically i thought to change the font family of footer to be equivalent with the rest of the body

**Comment by code-soham** [comment]
I think the footer font is looking great, so let's skip this for now😅

**Comment by manishbajagai2** [comment]
Oh ok, No issues, you may close this issue
