### ISSUE TITLE
Updating the Contributors Page

### ISSUE THREAD

**Issue by ronitblenz** [gdscjgec/Pictionary#93]
i would like to update the contributors page, Plz assign the issue to me and tag it as a medium issue

Thanks

**Comment by code-soham** [comment]
hi @ronitblenz , it'd be great if you specify what you want to work with

**Comment by ronitblenz** [comment]
The contributors page is out dated, I will update with latest information and maybe some more css tweaks
I will hope for a Medium tag for this issue

**Comment by code-soham** [comment]
Thanks for the suggestion but It is not needed right now as someone already suggested the revamp and the issue will be created soon! 😀
