### ISSUE TITLE
fix the title logo for rest of the pages

### ISSUE THREAD

**Issue by Jyoti6828** [gdscjgec/Pictionary#95]
### It should be like this :

![image](https://user-images.githubusercontent.com/78480983/153723581-4bd3fcd1-dd19-4521-a656-6dc5739a5cc8.png)

### but it looks like this :
![image](https://user-images.githubusercontent.com/78480983/153723557-9cdf283f-d99f-4745-a9ec-58613c56527a.png)

**Comment by Jyoti6828** [comment]
I want to work on this issue under JWOC.

**Comment by code-soham** [comment]
@Jyoti6828 Assigned!
