### ISSUE TITLE
Integrate GithubAPI in contributors Page

### ISSUE THREAD

**Issue by code-soham** [gdscjgec/Pictionary#97]
## 🚀 Feature

**A clear and concise description of what the feature is.**

Populate the contributor cards with data from the Github API :
https://api.github.com/repos/gdscjgec/Pictionary/contributors
https://api.github.com/users/<user_name>

**Comment by Aniket-508** [comment]
@code-soham I want to work on this issue under JWoC.

**Comment by code-soham** [comment]
@Sanga-Pal Assigned to you! 👍🏽
